- .github/workflows/publish-site.yaml
Adjust to index-machines.com for publishing.
> Switch Domain For Publishing

- doc/content/en/docs/mechanical-assembly/_index.md
Would resolve issue #241 if merged
> fix: Corrects BOM link in Mechanical assembly page

- doc/content/en/docs/reference/glossary/index.md
Definition of AOI comes from https://youtu.be/WmlhfJ_X49Y?t=440
> feat: Adds more definitions to glossary

- doc/content/en/docs/openpnp-setup/_index.md
- doc/content/en/docs/reference/_index.md
Adjusts weights of Reference and setup pages.
Would resolve issue #247 if merged.
Haven't yet figured out how to build the docs from the Docsy documentation so please do check before merging given if you agree with the reordering of sections
> [DOCS]: Adjusts Reference to be last section

- lfs.sh
- pnp/pcb/mobo/fp-lib-table
- pnp/pcb/mobo/sym-lib-table
This eases locking and unlocking LFS files,
The user specifies an operation and folder list and the script locks or unlocks all files one by one.
> LFS lock/unlock script

- README.md
Would resolve Issue #249 if merged, feel free to adjust the copy as required if you think the new section and link are helpful
> feat: Adds initial Documentation section in project readme

- README.md
- feeder/README.md
Would resolve issue #240 if merged
> fix: Corrects references to RING in feeder readme

- doc/content/en/docs/reference/print-settings/index.md
Would resolve issue #258 if merged
> feat: Adds initial print settings page to Reference section

- .github/ISSUE_TEMPLATE/mobo-bug.md
Scematic may be a technical word that we don't know the definition of so feel free to merge or refuse the pull request as required
> fix: Corrects small typo in mobo-bug issue template

- pnp/cad/export-3d-files.py
Allow script to run on Windows machines, uses the latest script from sphawes branch as base
> Update export-3d-files.py to work on Windows OS

- pnp/cad/slice-3d-files.py
Fixes the list of filenames to match the updated FDM names/designs recently merged into master
> Fix list of filenames to match recent FDM changes

- .gitignore
- pnp/code/openpnp2/machine.xml
Initial work on OpenPnP v2 configuration file. Feel free to contribute!
> OpenPnP v2 Configuration file

- openpnp/machine.xml
Video: https://drive.google.com/file/d/1-yhZjI18HwCzpKu55zW0i9QXEFoYyya4/view?usp=drivesdk
> Vision pipeline and parts being placed!

- .github/workflows/generate-bom.yaml
- pnp/cad/export-cad-bom.py
- pnp/cad/index_bom.md
This PR adds a GITHUB action and Python script to automatically parse the Freecad Assembly file to extract the part and fasteners into a single text file using mark down table.
> Auto generate/export BOM from FreeCAD assembly

- .github/workflows/publish-site.yaml
I have recently released 0.20.0 of the spellcheck GitHub action, I can see that you are using 0.11.0, so an update could be useful to you. Let me know if you have any issues with the proposal and I will try to accommodate
> Bumped spellcheck-github-action to latest version (0.20.0)

- .github/workflows/generate-feeder-pcb-artifacts.yaml
- .github/workflows/generate-mobo-pcb-artifacts.yaml
- .github/workflows/publish-site.yaml
- Creates doc website version
- Uploads PCB & Feeder artifacts
- Also gets #402  working.
> Update action configurations to support release.

- .github/workflows/publish-site.yaml
Updates to add 3D print generation into the document pipeline for proper output of the 3d print into page.
> Documentation Chagnes

- .github/workflows/publish-site.yaml
Removing 3D print work for now, ignoring tags and changing to new opulo URL.
> Doc CI Updates

- doc/content/en/docs/mechanical-assembly/printing-parts/index.md
Reverts index-machines/index#516
> Revert "Update index.md"

- doc/content/en/docs/mechanical-assembly/printing-parts/index.md
- Re-order information to better match cognitive flow.
- Note printer volume requirement.
- Emphasize the calibration print.
- Break various complex sentences into bullet lists.
> Revise the "Printing Parts" documentation

- doc/content/en/docs/mechanical-assembly/mount-x-to-y/index.md
> Docs: Change reference to FDM-0043 to FDM-0044

- .github/workflows/export-mcad.yaml
> Update FreeCAD to 0.21.2
